name: Playwright Tests

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment to test against"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - staging
          - production

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      BASE_URL: ${{ github.event.inputs.environment == 'staging' && 'https://staging.example.com' || (github.event.inputs.environment == 'production' && 'https://production.example.com' || 'https://dev.example.com') }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright Tests
        run: npx playwright test --project=Chromium

      - name: Upload Playwright report as artifact
        if: always()
        uses: actions/upload-artifact@v4.6.2
        with:
          name: playwright-report-${{ github.event.inputs.environment }}-${{ github.run_id }}
          path: playwright-report
