name: Playwright Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: [staging, production, dev] # List your environments here
    env:
      # You can define environment-specific variables here
      BASE_URL: ${{ matrix.environment == 'staging' && 'https://staging.example.com' || (matrix.environment == 'production' && 'https://example.com' || 'https://dev.example.com') }}
      # Optionally add other environment-specific variables like:
      # API_KEY: ${{ secrets.API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright Tests
        run: npx playwright test --project=${{ matrix.environment }} # Optional: specify a project based on environment

      - name: Upload Playwright report as artifact
        if: always()
        uses: actions/upload-artifact@v4.6.2
        with:
          name: playwright-report-${{ matrix.environment }}-${{ github.run_id }} # Adding matrix.environment and run_id for uniqueness
          path: playwright-report
